<?php

/**
 * @file
 * status_time.module
 * Developer: Danilevsky Kirill k.danilevsky@gmail.com
 * version 1.2
 */

/**
 * Implementation of hook_help.
 * 
 */
function status_time_help($path, $arg) {
  switch ($path) {
    case "admin/help#status_time":
      return t("<p>This module allow users to assign the lifetime their account.</p>");
  }
}

/**
 * Implementation of hook_field_access.
 * 
 * Our field displayed only admin.
 */
function status_time_field_access($op, $field, $entity_type, $entity, $account) {
  if ($op == 'edit' && $field['field_name'] == 'st_field_end_date') {
    if (!user_access('administer users', $account = NULL)) {
      return FALSE;
    }
  }
}

/**
 * Implementation of hook_form_form_id_alter.
 * 
 * Register new user.
 * Edit in st_field_end_date - input format. Set default value = ''. 
 */
function status_time_form_user_register_form_alter(&$form, &$form_state) {
  $form['st_field_end_date'][LANGUAGE_NONE][0]['#default_value']['value'] = '';
  $form_state['field']['st_field_end_date']['und']['instance']['widget']['settings']['input_format'] = 'm/d/Y';
  return $form;
}

/**
 * Implementation of hook_form_form_id_alter.
 * 
 * Edit user profile.
 * Edit in st_field_end_date - input format.
 */
function status_time_form_user_profile_form_alter(&$form, &$form_state) {
  $form_state['field']['st_field_end_date']['und']['instance']['widget']['settings']['input_format'] = 'm/d/Y';
  return $form;
}

/**
 * Implementation of hook_cron().
 * 
 * Change status user's account if date is not actual.
 */
function status_time_cron() {
  $query = db_select('field_data_st_field_end_date', 'f');
  $query->leftJoin('users', 'u', 'u.uid=f.entity_id AND u.uid>1');
  $query->condition('u.status', 1);
  $query->where('UNIX_TIMESTAMP(NOW()) > f.st_field_end_date_value');
  $query->fields('f', array('entity_id'));
  $result = $query->execute();
  foreach ($result as $key => $value) {
    db_update('users')
        ->fields(array('status' => 0))
        ->condition('uid', $value->entity_id)
        ->execute();
  }
}
